# Generated by Django 5.2.17 on 2026-08-17 12:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureSet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("single", "单图"),
                            ("left_center_right", "左中右三图"),
                            ("video", "视频"),
                        ],
                        max_length=24,
                    ),
                ),
                ("client_capture_id", models.UUIDField(unique=True)),
                ("requires_manual_review", models.BooleanField(default=False)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "采集组",
                "verbose_name_plural": "采集组",
            },
        ),
        migrations.CreateModel(
            name="FarmOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("erp_external_id", models.CharField(blank=True, max_length=128)),
                ("sync_version", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "猪场组织",
                "verbose_name_plural": "猪场组织",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buildings",
                        to="inventory.farmorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "楼栋",
                "verbose_name_plural": "楼栋",
                "ordering": ["organization__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("media_deleted", "媒体删除"),
                            ("media_override", "媒体管理员覆盖"),
                            ("count_confirmed", "数量确认"),
                            ("count_corrected", "数量更正"),
                            ("erp_sync", "ERP 同步"),
                            ("package_committed", "上传包提交"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="inventory.farmorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计事件",
                "verbose_name_plural": "审计事件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InferenceJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "已排队"),
                            ("running", "运行中"),
                            ("succeeded", "成功"),
                            ("review_required", "待复核"),
                            ("failed", "失败"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("provider_key", models.CharField(max_length=64)),
                ("model_key", models.CharField(blank=True, max_length=128)),
                ("model_version", models.CharField(blank=True, max_length=128)),
                ("model_checksum", models.CharField(blank=True, max_length=128)),
                ("adapter_version", models.CharField(default="v1", max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_detail", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "capture_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inference_jobs",
                        to="inventory.captureset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CountResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_count", models.PositiveIntegerField()),
                ("detections", models.JSONField(blank=True, default=list)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="inventory.inferencejob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "aggregation_method",
                    models.CharField(
                        choices=[("mean", "算术平均")], default="mean", max_length=16
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="inventory.farmorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点周期",
                "verbose_name_plural": "盘点周期",
            },
        ),
        migrations.CreateModel(
            name="InventorySession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("processing", "推理中"),
                            ("review_required", "待人工复核"),
                            ("confirmed", "已确认"),
                            ("failed", "失败"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("manual_count", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="inventory.inventorycampaign",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_inventory_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inventory_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点任务",
                "verbose_name_plural": "盘点任务",
                "ordering": ["-business_date", "pen__code"],
            },
        ),
        migrations.AddField(
            model_name="inferencejob",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inference_jobs",
                to="inventory.inventorysession",
            ),
        ),
        migrations.AddField(
            model_name="captureset",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capture_sets",
                to="inventory.inventorysession",
            ),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "view_position",
                    models.CharField(
                        choices=[
                            ("single", "单图"),
                            ("left", "左"),
                            ("center", "中"),
                            ("right", "右"),
                            ("video", "视频"),
                        ],
                        max_length=12,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=128)),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("perceptual_hash", models.CharField(blank=True, max_length=128)),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                ("roi", models.JSONField(blank=True, default=dict)),
                ("exif", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "可用"),
                            ("locked", "已锁定"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capture_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_assets",
                        to="inventory.captureset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_assets",
                        to="inventory.farmorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点媒体",
                "verbose_name_plural": "盘点媒体",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("operator", "现场操作员"),
                            ("reviewer", "审核员"),
                            ("admin", "组织管理员"),
                        ],
                        default="operator",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="inventory.farmorganization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "组织成员",
                "verbose_name_plural": "组织成员",
            },
        ),
        migrations.CreateModel(
            name="Pen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("capture_guidance", models.JSONField(blank=True, default=dict)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pens",
                        to="inventory.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "栏舍",
                "verbose_name_plural": "栏舍",
                "ordering": ["building__organization__code", "building__code", "code"],
            },
        ),
        migrations.AddField(
            model_name="inventorysession",
            name="pen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_sessions",
                to="inventory.pen",
            ),
        ),
        migrations.CreateModel(
            name="UploadPackage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_blobs", "待上传文件"),
                            ("awaiting_manifest", "待上传清单"),
                            ("ready_to_commit", "待提交"),
                            ("committed", "已提交"),
                            ("failed", "失败"),
                        ],
                        default="awaiting_blobs",
                        max_length=24,
                    ),
                ),
                ("manifest", models.JSONField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_packages",
                        to="inventory.inventorysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传包",
                "verbose_name_plural": "上传包",
            },
        ),
        migrations.CreateModel(
            name="UploadBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_id", models.UUIDField()),
                ("relative_path", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("content_type", models.CharField(max_length=128)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blobs",
                        to="inventory.uploadpackage",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_building_code_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.UniqueConstraint(
                fields=("organization", "sha256"),
                name="unique_media_sha_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="unique_user_membership_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="pen",
            constraint=models.UniqueConstraint(
                fields=("building", "code"), name="unique_pen_code_per_building"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadpackage",
            constraint=models.UniqueConstraint(
                fields=("session", "idempotency_key"),
                name="unique_package_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadblob",
            constraint=models.UniqueConstraint(
                fields=("package", "asset_id"), name="unique_blob_asset_per_package"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadblob",
            constraint=models.UniqueConstraint(
                fields=("package", "relative_path"), name="unique_blob_path_per_package"
            ),
        ),
    ]
